"""add category_id to listing_drafts

Revision ID: 2402757ad5c9
Revises: 579e1c82033d
Create Date: 2026-05-15 20:45:10.394458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2402757ad5c9'
down_revision: Union[str, Sequence[str], None] = '579e1c82033d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_drafts', sa.Column('meli_item_id', sa.String(), nullable=True))
    op.add_column('listing_drafts', sa.Column('meli_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_drafts', 'meli_url')
    op.drop_column('listing_drafts', 'meli_item_id')
    # ### end Alembic commands ###
