"""add category_id to listing_drafts

Revision ID: 30fccd8e1e49
Revises: 43c45366f9b4
Create Date: 2026-05-15 20:11:50.128268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30fccd8e1e49'
down_revision: Union[str, Sequence[str], None] = '43c45366f9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_drafts', sa.Column('category_id', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('listing_drafts', 'category_id')
    # ### end Alembic commands ###
