"""add remaining fields to complete the request

Revision ID: 579e1c82033d
Revises: 30fccd8e1e49
Create Date: 2026-05-15 20:35:48.961893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '579e1c82033d'
down_revision: Union[str, Sequence[str], None] = '30fccd8e1e49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('listing_drafts', sa.Column('condition', sa.String(), nullable=True))
    op.add_column('listing_drafts', sa.Column('listing_type_id', sa.String(), nullable=True))
    op.add_column('listing_drafts', sa.Column('available_quantity', sa.Integer(), nullable=True))
    op.add_column('listing_drafts', sa.Column('pictures', sa.JSON(), nullable=True))
    op.alter_column('listing_drafts', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('listing_drafts', 'category_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('listing_drafts', 'pictures')
    op.drop_column('listing_drafts', 'available_quantity')
    op.drop_column('listing_drafts', 'listing_type_id')
    op.drop_column('listing_drafts', 'condition')
    # ### end Alembic commands ###
